"""Update media tracking

Revision ID: dcfce21daa08
Revises: 
Create Date: 2025-06-01 13:51:42.944865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfce21daa08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('user_media_user_id_media_id_key'), 'user_media', type_='unique')
    op.create_unique_constraint('uix_user_media', 'user_media', ['user_id', 'media_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_media', 'user_media', type_='unique')
    op.create_unique_constraint(op.f('user_media_user_id_media_id_key'), 'user_media', ['user_id', 'media_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('media', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
