"""Add media tracking and review system

Revision ID: f62aadd719dc
Revises: dcfce21daa08
Create Date: 2025-06-02 04:15:46.743353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62aadd719dc'
down_revision: Union[str, None] = 'dcfce21daa08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('media', sa.Column('genre', sa.String(length=100), nullable=True))
    op.add_column('media', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('user_media', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('user_media', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('user_media', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'user_media', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_media', 'media', ['media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_media', type_='foreignkey')
    op.drop_constraint(None, 'user_media', type_='foreignkey')
    op.alter_column('user_media', 'rating',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('user_media', 'completed_at')
    op.drop_column('user_media', 'started_at')
    op.drop_column('media', 'image_url')
    op.drop_column('media', 'release_year')
    op.drop_column('media', 'genre')
    op.drop_table('reviews')
    # ### end Alembic commands ###
